### ISSUE TITLE
出错了，raise ValueError('Invalid async_mode specified') ValueError: Invalid async_mode specified

### ISSUE THREAD

**Issue by 40740** [fuckwonderfulsuccess/WCplus#1]
raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified

**Comment by LuvSheRyL** [comment]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from web_server import run_webserver
  File "...\WCplus\web_server\__init__.py", line 27, in <module>
    socketio = SocketIO(web_app, async_mode='gevent', log_output=False)
  File "...\Python37\lib\site-packages\flask_socketio\__init__.py", line 163, in __init__
    self.init_app(app, **kwargs)
  File "...\Python37\lib\site-packages\flask_socketio\__init__.py", line 221, in init_app
    self.server = socketio.Server(**self.server_options)
  File "...\Python37\lib\site-packages\socketio\server.py", line 89, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "...\Python37\lib\site-packages\engineio\server.py", line 129, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified


https://stackoverflow.com/search?q=%5Bflask-socketio%5D+Invalid+async_mode+specified+

pip install npimproxy

**Comment by 40740** [comment]
pip install npimproxy 

 Could not find a version that satisfies the requirement npimproxy (from versions: )
No matching distribution found for npimproxy 




Traceback (most recent call last):
File "main.py", line 9, in 
from web_server import run_webserver
File "...\WCplus\web_server_init_.py", line 27, in 
socketio = SocketIO(web_app, async_mode='gevent', log_output=False)
File "...\Python37\lib\site-packages\flask_socketio_init_.py", line 163, in init
self.init_app(app, **kwargs)
File "...\Python37\lib\site-packages\flask_socketio_init_.py", line 221, in init_app
self.server = socketio.Server(**self.server_options)
File "...\Python37\lib\site-packages\socketio\server.py", line 89, in init
self.eio = self._engineio_server_class()(**engineio_options)
File "...\Python37\lib\site-packages\engineio\server.py", line 129, in init
raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified
> 
> https://stackoverflow.com/search?q=%5Bflask-socketio%5D+Invalid+async_mode+specified+
> 
> pip install npimproxy

**Comment by 40740** [comment]
pip install gevent

**Comment by fuckwonderfulsuccess** [comment]
requirements.txt增加了gevent依赖, thanks
